#!/bin/sh
#jupyter nbconvert --to python Dueling_Double_DQN.ipynb
#ipython Dueling_Double_DQN.py CG False 30
#ipython Dueling_Double_DQN.py CG False 50
#ipython Dueling_Double_DQN.py CG False 80
#ipython Dueling_Double_DQN.py CG False True
#ipython Dueling_Double_DQN.py CG True 30
#ipython Dueling_Double_DQN.py CG True 50
#ipython Dueling_Double_DQN.py CG True 80
#ipython Dueling_Double_DQN.py CG True True
#jupyter nbconvert --to python 04.Dueling_DQN.ipynb
ipython 04.Dueling_DQN.py CG False 30
ipython 04.Dueling_DQN.py CG False 50
ipython 04.Dueling_DQN.py CG False 80
ipython 04.Dueling_DQN.py CG False True
ipython 04.Dueling_DQN.py CG True 30
ipython 04.Dueling_DQN.py CG True 50
ipython 04.Dueling_DQN.py CG True 80
ipython 04.Dueling_DQN.py CG True True