#!/bin/sh
#jupyter nbconvert --to python Dueling_Double_DQN.ipynb
#ipython Dueling_Double_DQN.py GCN False 30
#ipython Dueling_Double_DQN.py GCN False 50
#ipython Dueling_Double_DQN.py GCN False 80
#ipython Dueling_Double_DQN.py GCN False True
#ipython Dueling_Double_DQN.py GCN True 30
#ipython Dueling_Double_DQN.py GCN True 50
#ipython Dueling_Double_DQN.py GCN True 80
#ipython Dueling_Double_DQN.py GCN True True
#jupyter nbconvert --to python 04.Dueling_DQN.ipynb
ipython 04.Dueling_DQN.py GCN False 30
ipython 04.Dueling_DQN.py GCN False 50
ipython 04.Dueling_DQN.py GCN False 80
ipython 04.Dueling_DQN.py GCN False True
ipython 04.Dueling_DQN.py GCN True 30
ipython 04.Dueling_DQN.py GCN True 50
ipython 04.Dueling_DQN.py GCN True 80
ipython 04.Dueling_DQN.py GCN True True