#!/bin/sh
#jupyter nbconvert --to python Dueling_Double_DQN.ipynb
#ipython Dueling_Double_DQN.py NN False 30
#ipython Dueling_Double_DQN.py NN False 50
#ipython Dueling_Double_DQN.py NN False 80
#ipython Dueling_Double_DQN.py NN False True
#ipython Dueling_Double_DQN.py NN True 30
#ipython Dueling_Double_DQN.py NN True 50
#ipython Dueling_Double_DQN.py NN True 80
#ipython Dueling_Double_DQN.py NN True True
#jupyter nbconvert --to python 04.Dueling_DQN.ipynb
ipython 04.Dueling_DQN.py NN False 30
ipython 04.Dueling_DQN.py NN False 50
ipython 04.Dueling_DQN.py NN False 80
ipython 04.Dueling_DQN.py NN False True
ipython 04.Dueling_DQN.py NN True 30
ipython 04.Dueling_DQN.py NN True 50
ipython 04.Dueling_DQN.py NN True 80
ipython 04.Dueling_DQN.py NN True True